// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BPCalculator.BDDTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BloodPressureCategoryEvaluationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "bloodpressure"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Blood Pressure Category Evaluation", "  To ensure accurate BP classification\r\n  As a health application\r\n  I want to de" +
                "termine the correct BP category based on systolic and diastolic values", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BPCalculator.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BPCalculator.feature.ndjson", 16);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Classify valid blood pressure values")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Classify valid blood pressure values")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bloodpressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("category")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("85", "55", "Low", "0", null, DisplayName="Classify valid blood pressure values(85,55,Low,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("95", "65", "Ideal", "1", null, DisplayName="Classify valid blood pressure values(95,65,Ideal,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("118", "78", "Ideal", "2", null, DisplayName="Classify valid blood pressure values(118,78,Ideal,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("125", "79", "PreHigh", "3", null, DisplayName="Classify valid blood pressure values(125,79,PreHigh,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("139", "85", "PreHigh", "4", null, DisplayName="Classify valid blood pressure values(139,85,PreHigh,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("140", "88", "High", "5", null, DisplayName="Classify valid blood pressure values(140,88,High,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("150", "95", "High", "6", null, DisplayName="Classify valid blood pressure values(150,95,High,6)")]
        public async global::System.Threading.Tasks.Task ClassifyValidBloodPressureValues(string systolic, string diastolic, string expected, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "category"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            argumentsOfScenario.Add("Expected", expected);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Classify valid blood pressure values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync(string.Format("my systolic value is {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
    await testRunner.AndAsync(string.Format("my diastolic value is {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.WhenAsync("I evaluate the BP category", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync(string.Format("the result should be \"{0}\"", expected), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Systolic must be higher than diastolic")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Systolic must be higher than diastolic")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bloodpressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("invalid-reading")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("80", "80", "7", null, DisplayName="Systolic must be higher than diastolic(80,80,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("90", "100", "8", null, DisplayName="Systolic must be higher than diastolic(90,100,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "130", "9", null, DisplayName="Systolic must be higher than diastolic(120,130,9)")]
        public async global::System.Threading.Tasks.Task SystolicMustBeHigherThanDiastolic(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "invalid-reading"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Systolic must be higher than diastolic", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
    await testRunner.GivenAsync(string.Format("my systolic value is {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
    await testRunner.AndAsync(string.Format("my diastolic value is {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.WhenAsync("I evaluate the BP category", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("an invalid reading error should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Validate systolic and diastolic input range")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate systolic and diastolic input range")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Evaluation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("bloodpressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("out-of-range")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("60", "70", "Invalid Systolic Value", "10", null, DisplayName="Validate systolic and diastolic input range(60,70,Invalid Systolic Value,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("200", "70", "Invalid Systolic Value", "11", null, DisplayName="Validate systolic and diastolic input range(200,70,Invalid Systolic Value,11)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "30", "Invalid Diastolic Value", "12", null, DisplayName="Validate systolic and diastolic input range(120,30,Invalid Diastolic Value,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "150", "Invalid Diastolic Value", "13", null, DisplayName="Validate systolic and diastolic input range(120,150,Invalid Diastolic Value,13)")]
        public async global::System.Threading.Tasks.Task ValidateSystolicAndDiastolicInputRange(string systolic, string diastolic, string message, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "out-of-range"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            argumentsOfScenario.Add("Message", message);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate systolic and diastolic input range", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
    await testRunner.GivenAsync(string.Format("my systolic value is {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
    await testRunner.AndAsync(string.Format("my diastolic value is {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("I validate the BP input range", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync(string.Format("the validation should fail with \"{0}\"", message), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
